# Generated by Django 5.1.1 on 2024-10-09 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="UBIGEO de la Provincia", max_length=20, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(blank=True, help_text="UBIGEO del Distrito", max_length=20, null=True),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="locations.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distrito",
                "verbose_name_plural": "Distritos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PopulationCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="UBIGEO del Centro Poblado",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "population_center_id_datass",
                    models.CharField(help_text="ID de Centro Poblado en DATASS", max_length=50),
                ),
                (
                    "survey_id",
                    models.CharField(
                        blank=True, help_text="ID de Encuesta en DATASS", max_length=50, null=True
                    ),
                ),
                (
                    "latitude_inei",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitud en grados decimales según INEI",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude_inei",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitud en grados decimales según INEI",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "latitude_datass",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitud en grados decimales según DATASS",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude_datass",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitud en grados decimales según DATASS",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="population_centers",
                        to="locations.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro Poblado",
                "verbose_name_plural": "Centros Poblados",
                "ordering": ["name"],
                "unique_together": {("code", "district")},
            },
        ),
    ]
